Added the absolute state of KDE software that should get released in lockstep with the KDE megarelease
Greybeard-Entertainment/pages pull request #9
Opened 2024-03-02 09:47 UTC by appetrosyan

2024-03-23 18:08 UTC, 6r1d submitted a review, later dismissed

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +This is a tiny discussion of why if you're writing your GUI in rust, life is
```suggestion
This is a tiny discussion of why if you're writing your GUI in Rust, life is
```

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  Have to fuck around with the build system.
```suggestion
  For starters, you have to fuck around with the build system.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  Have to fuck around with the Qt abstractions rather than circumvent them in a
```suggestion
  Plus, you have to fuck around with the Qt abstractions rather than circumvent them in a
```

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  Where in this error message can you find mention of either the missing file:
Could you add a footnote (not necessarily in this PR) that gives some hint on determining a real filename, or is it just the use of search engines and forums? Or, maybe, a piece of the code/Makefile/whatever contains something pointing towards a proper name?

While I think I should know this already, I do remember many cases where it was quite different for different packages, and I had no automatic way to do that. I understand the idea that the change needs to be made, but I'm thinking in short-term here.

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  Error handling.  Every function is both potentially fallible and never
```suggestion
  Error handling is not any easier.  Every function is both potentially fallible and never
```

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  to a skill issue.  WHat about the potential productivity?
```suggestion
  to a skill issue.  What about the potential productivity?
```

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  likely going to be more productive.  Inheritance, the C++ macros are
I think the sentence about the inheritance should be paraphrased to be more clear.

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  I get almost none of the benefits of Rust, because of the exposure to Qt.
```suggestion
  I get almost none of the benefits of Rust, because of its exposure to Qt.
```

(I'm not sure how applicable it is.)

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  features of a C++ class.  Just use C++ then.  C++ isn't that terrible, and it
```suggestion
  features of a C++ class.  At this point, using C++ becomes easier:  C++ isn't that terrible, and it
```

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  one can package the problem into slightly (and only slightly) less defective
less defective compared to what?

2024-03-23 18:08 UTC, 6r1d commented on docs/are_we_gui_yet.org
> +  it is not even not standard C++ it is not even the latest standard /of/ C++
Please elaborate on the "not even not" part.

2024-03-23 18:08 UTC, 6r1d commented on docs/rust-is-oop.org
> +But I will argue that Rust is truer to the original vision of OOP than the half-hearted attempts in Python, and the principled, though baroque approach adopted in Java.  It is not quiet on the same l
```suggestion
But I will argue that Rust is truer to the original vision of OOP than the half-hearted attempts in Python, and the principled, though baroque approach adopted in Java.  It is not quite on the same level as SmallTalk, JavaScript or Objective C, but those languages are largely misunderstood.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/rust-is-oop.org
> +But I will argue that Rust is truer to the original vision of OOP than the half-hearted attempts in Python, and the principled, though baroque approach adopted in Java.  It is not quiet on the same l
```suggestion
I will argue that Rust is truer to the original vision of OOP than the half-hearted attempts in Python, and the principled, though baroque approach adopted in Java.  It is not quiet on the same level as SmallTalk, JavaScript or Objective C, but those languages are largely misunderstood.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/rust-is-oop.org
> +The first key assumption is that there is a clear hierarchy.  Within the C world, one would make a table for all unique functions and then point each individual entity's behaviour function pointer to
```suggestion
The first key assumption is that there is a clear hierarchy.  Within the C world, one would make a table for all unique functions and then point each individual entity's behaviour function pointer to that function.  So adding each new species entity isn't a hard task.  But the amount of work is certainly sub-optimal.  So one needs to spend a bit more time and see that there are categories of herbivore and Carnivore, vertebrate vs invertebrate, and to come up with a tree of inheritance that tends to categorise animals by which behaviour they engage in.  Sometimes, if the behaviour follows from another behaviour, and as a crucial difference from the function pointer approach, one can make a shortcut.  Java, Rust, Haskell, and C++ all do it that way.   But the devil is in the details.
```
```suggestion
The first key assumption is that there is a clear hierarchy.  Within the C world, one would make a table for all unique functions and then point each individual entity's behaviour function pointer to that function.  So adding each new species entity isn't a hard task.  But the amount of work is certainly sub-optimal.  So one needs to spend a bit more time and see that there are categories of herbivore and carnivore, vertebrate vs invertebrate, and to come up with a tree of inheritance that tends to categorise animals by which behaviour they engage in.  Sometimes, if the behaviour follows from another behaviour, and as a crucial difference from the function pointer approach, one can make a shortcut.  Java, Rust, Haskell, and C++ all do it that way.   But the devil is in the details.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/rust-is-oop.org
> +With Java and C++, the assumption is that the participation in a particular way is tied to the object's self.  A cat, isn't just something that implements =Carnivore= but rather being a =Cat= is inex
- Can it be written that way or is it written like "evolved convergently"?
- Do you point out the part of classification through the capitalisation?

2024-03-23 18:08 UTC, 6r1d commented on docs/rust-is-oop.org
> +Now it might seem that because the technical difference is subtle, that the resulting code is also different only subtly.  But that is far from the case.  In Fallout New Vegas, the vehicles are hats
```suggestion
Now it might seem that because the technical difference is subtle, that the resulting code is also different only subtly.  But that is far from the case.  In “Fallout New Vegas”, the vehicles are hats attached to an entity.  This is not what a non-technical person would assume does the walking, but the way the code is organised makes it harder to do anything else.  With Haskell and Rust, the act of moving is less tightly coupled, and that gives one more room to manoeuvre with semantics.  This approach is more granular, and discourages trying to model every aspect of the domain taxonomically.  You're writing procedural code where it's more convenient, but if you need to impose a hierarchy of interfaces, they are there and very minimal.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/rust-is-oop.org
> +Well, in Rust pretty much all the same is present.  You can choose the visibility of an object's properties almost universally and granular.  This is as good as Java, because I can control the access
```suggestion
Well, in Rust pretty much all the same is present.  You can choose the visibility of an object's properties almost universally, in a granular fashion.  This is as good as Java, because I can control the access to any field, without having to change its place.  Moreover, unlike having to remember which vague statement corresponds to which scope, I have a simple =crate= meaning "translation unit", =super= meaning "also in the enclosing module", and plain, meaning "in general".  This makes it more likely that I won't frivolously add a "getter" and a "setter" which essentially do the exact same as public access would.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/rust-is-oop.org
> +[fn:3]:  Outside the OOP world, in a procedural language like C, every field of every structure is always available.  So you can always do =thing.state= to read the state of an object.  In OOP, this
"Machine", not "software"? Does it imply some CS term?

2024-03-23 18:08 UTC, 6r1d commented on docs/the-absolute-state-of-kde-software.org
> +Spreadsheets? This is slightly different.  Only slightly, because there seems to be consensus that the cell-based accounting system that is inherent in spreadsheets is not a great solution long-term.
```suggestion
Spreadsheets? This is slightly different.  Only slightly, because there seems to be a consensus that the cell-based accounting system that is inherent in spreadsheets is not a great long-term solution.   Do you know of many accounting firms that use Excel directly and if you did, would you trust them?  More importantly, the data is often either shared in a format in which the spreadsheet is irrelevant (/e.g./ CSV) or in which accurate data reproduction with its limitations is paramount.  Believe it or not, there are good reasons to believe that some of the NHS is still running on the original binary Excel format, not the new-fangled XML-based one.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/the-absolute-state-of-kde-software.org
> +And overleaf is the bare minimum.  I cannot fathom working on my research paper in Kile, given how much AucTex, RefTex, Git and CDLaTeX save me in terms of hassle.  And if I really needed to do onlin
```suggestion
And Overleaf is the bare minimum.  I cannot fathom working on my research paper in Kile, given how much AucTex, RefTex, Git and CDLaTeX save me in terms of hassle.  And if I really needed to do online collaborative editing with someone who was using a similar technology, I would use `crdt.el`.  Your specialised program should not be overshadowed by a text editor maintained by a bunch of weirdos like me.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/the-absolute-state-of-kde-software.org
> +Dolphin is a file manager that fundamentally understands that you want to manage files.  It's not quite the swiss army knife that konqueror used to be but that is for the better.  Konqueror would hav
```suggestion
Dolphin is a file manager that fundamentally understands that you want to manage files. It's not quite the Swiss Army knife that Konqueror used to be, but that is for the better. Konqueror would have been a mediocre browser, and trying to make it passable would have taken resources away from making it a good file manager. And there's a lot to Dolphin.
```

2024-03-23 18:08 UTC, 6r1d commented on docs/the-absolute-state-of-kde-software.org
> +Want to have a UI that resembles YouTube with local videos, you can do it, just crank up the preview sizes.  Want to make things as clear as a table, sure, there's that view too.  OK, how about featu
I think you can do much more than preview sizes, but this is rarely done and it's being done in different software.

Let's say I'm walking around and filming city an hour. How about storing section previews where the time or color palette changed a lot? Maybe I'm filming / visiting some nice mall I want to see. TL;DR, a lot more can be done about the preview mechanism.

2024-03-29 21:26 UTC, appetrosyan commented on docs/rust-is-oop.org
> +With Java and C++, the assumption is that the participation in a particular way is tied to the object's self.  A cat, isn't just something that implements =Carnivore= but rather being a =Cat= is inex
This is the convention of Rust and Haskell to capitalise the Types of things.

2024-03-29 21:55 UTC, appetrosyan commented on docs/rust-is-oop.org
> +[fn:3]:  Outside the OOP world, in a procedural language like C, every field of every structure is always available.  So you can always do =thing.state= to read the state of an object.  In OOP, this
Yes, we are talking about Turing machines.

2024-05-11 18:56 UTC, 6r1d requested changes
I believe that index can be updated a bit

2024-05-12 13:10 UTC, merged